# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8Nai12COFyszhmMtKautBNqwZ-D_9Gz
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt